package com.mylibrary.core.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import com.mylibrary.core.domain.model.ColorSource

/**
 * The app's colour schemes, one light and one dark per [ColorSource].
 *
 * **These are generated, and the generator is in the repository.**
 * `tools/material_palette.py` builds each scheme from a seed the way Material 3 specifies: six tonal
 * palettes at fixed chromas around the seed's hue, and every role reading a named tone of one of
 * them. Run it after changing a seed; it rewrites this file and checks itself against Google's
 * published baseline palette before it does.
 *
 * That check is the reason to trust the numbers below. A hand-written palette can only be reviewed
 * by eye, and an eye cannot see that `onSurfaceVariant` is the wrong *tone* rather than the wrong
 * colour — it just looks slightly off, on one screen, in one brightness. Generated from a verified
 * mapping, every pairing in here is the one Material guarantees.
 *
 * [ColorSource.TEAL] is deliberately absent: it is the palette the app shipped with, hand-authored
 * in `Color.kt`, and regenerating it would change the app's own colour for no reason a reader asked
 * for. [ColorSource.WALLPAPER] has no scheme at all — it is the device's, resolved at runtime.
 */

internal val PURPLELightColors = lightColorScheme(
    primary = Color(0xFF6750A4),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE4DFFF),
    onPrimaryContainer = Color(0xFF270255),
    inversePrimary = Color(0xFFCBBEFF),
    secondary = Color(0xFF605B72),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE4DFFA),
    onSecondaryContainer = Color(0xFF1D192B),
    tertiary = Color(0xFF7C5263),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFD8E7),
    onTertiaryContainer = Color(0xFF320F1F),
    error = Color(0xFFB4271F),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD4),
    onErrorContainer = Color(0xFF410000),
    background = Color(0xFFFCFCFF),
    onBackground = Color(0xFF1C1B1F),
    surface = Color(0xFFFCFCFF),
    onSurface = Color(0xFF1C1B1F),
    surfaceVariant = Color(0xFFE3E1ED),
    onSurfaceVariant = Color(0xFF474550),
    outline = Color(0xFF787681),
    outlineVariant = Color(0xFFC7C5D1),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF313034),
    inverseOnSurface = Color(0xFFF1F0F6),
    surfaceDim = Color(0xFFDAD9DF),
    surfaceBright = Color(0xFFFAF9FE),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF4F3F9),
    surfaceContainer = Color(0xFFEEEDF3),
    surfaceContainerHigh = Color(0xFFE8E7ED),
    surfaceContainerHighest = Color(0xFFE3E2E7),
    surfaceTint = Color(0xFF6750A4),
)

internal val PURPLEDarkColors = darkColorScheme(
    primary = Color(0xFFCBBEFF),
    onPrimary = Color(0xFF3A1F6E),
    primaryContainer = Color(0xFF503789),
    onPrimaryContainer = Color(0xFFE4DFFF),
    inversePrimary = Color(0xFF6750A4),
    secondary = Color(0xFFC8C3DD),
    onSecondary = Color(0xFF322E42),
    secondaryContainer = Color(0xFF484459),
    onSecondaryContainer = Color(0xFFE4DFFA),
    tertiary = Color(0xFFEABACC),
    onTertiary = Color(0xFF4A2535),
    tertiaryContainer = Color(0xFF623B4B),
    onTertiaryContainer = Color(0xFFFFD8E7),
    error = Color(0xFFFFB4A8),
    onError = Color(0xFF690001),
    errorContainer = Color(0xFF930003),
    onErrorContainer = Color(0xFFFFDAD4),
    background = Color(0xFF1C1B1F),
    onBackground = Color(0xFFE3E2E7),
    surface = Color(0xFF1C1B1F),
    onSurface = Color(0xFFE3E2E7),
    surfaceVariant = Color(0xFF474550),
    onSurfaceVariant = Color(0xFFC7C5D1),
    outline = Color(0xFF918F9B),
    outlineVariant = Color(0xFF474550),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE3E2E7),
    inverseOnSurface = Color(0xFF313034),
    surfaceDim = Color(0xFF141317),
    surfaceBright = Color(0xFF39393D),
    surfaceContainerLowest = Color(0xFF0E0E11),
    surfaceContainerLow = Color(0xFF1C1B1F),
    surfaceContainer = Color(0xFF201F23),
    surfaceContainerHigh = Color(0xFF2A292E),
    surfaceContainerHighest = Color(0xFF353438),
    surfaceTint = Color(0xFFCBBEFF),
)

internal val BLUELightColors = lightColorScheme(
    primary = Color(0xFF00629E),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFCAE6FF),
    onPrimaryContainer = Color(0xFF001D34),
    inversePrimary = Color(0xFF92CCFF),
    secondary = Color(0xFF4D6072),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCFE5F9),
    onSecondaryContainer = Color(0xFF0C1D2B),
    tertiary = Color(0xFF68577B),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFECDCFF),
    onTertiaryContainer = Color(0xFF241433),
    error = Color(0xFFB4271F),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD4),
    onErrorContainer = Color(0xFF410000),
    background = Color(0xFFFAFDFF),
    onBackground = Color(0xFF191C1F),
    surface = Color(0xFFFAFDFF),
    onSurface = Color(0xFF191C1F),
    surfaceVariant = Color(0xFFD9E4ED),
    onSurfaceVariant = Color(0xFF3F484F),
    outline = Color(0xFF6F7881),
    outlineVariant = Color(0xFFBEC8D1),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF2D3134),
    inverseOnSurface = Color(0xFFEDF1F6),
    surfaceDim = Color(0xFFD6DBDF),
    surfaceBright = Color(0xFFF5FAFE),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFEFF4F8),
    surfaceContainer = Color(0xFFEAEEF3),
    surfaceContainerHigh = Color(0xFFE4E9ED),
    surfaceContainerHighest = Color(0xFFDEE3E7),
    surfaceTint = Color(0xFF00629E),
)

internal val BLUEDarkColors = darkColorScheme(
    primary = Color(0xFF92CCFF),
    onPrimary = Color(0xFF003355),
    primaryContainer = Color(0xFF004A79),
    onPrimaryContainer = Color(0xFFCAE6FF),
    inversePrimary = Color(0xFF00629E),
    secondary = Color(0xFFB4C9DD),
    onSecondary = Color(0xFF213241),
    secondaryContainer = Color(0xFF364959),
    onSecondaryContainer = Color(0xFFCFE5F9),
    tertiary = Color(0xFFD2BFE8),
    onTertiary = Color(0xFF39294A),
    tertiaryContainer = Color(0xFF504062),
    onTertiaryContainer = Color(0xFFECDCFF),
    error = Color(0xFFFFB4A8),
    onError = Color(0xFF690001),
    errorContainer = Color(0xFF930003),
    onErrorContainer = Color(0xFFFFDAD4),
    background = Color(0xFF191C1F),
    onBackground = Color(0xFFDEE3E7),
    surface = Color(0xFF191C1F),
    onSurface = Color(0xFFDEE3E7),
    surfaceVariant = Color(0xFF3F484F),
    onSurfaceVariant = Color(0xFFBEC8D1),
    outline = Color(0xFF88929B),
    outlineVariant = Color(0xFF3F484F),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFDEE3E7),
    inverseOnSurface = Color(0xFF2D3134),
    surfaceDim = Color(0xFF111417),
    surfaceBright = Color(0xFF363A3D),
    surfaceContainerLowest = Color(0xFF0B0E11),
    surfaceContainerLow = Color(0xFF191C1F),
    surfaceContainer = Color(0xFF1D2023),
    surfaceContainerHigh = Color(0xFF272A2D),
    surfaceContainerHighest = Color(0xFF323538),
    surfaceTint = Color(0xFF92CCFF),
)

internal val GREENLightColors = lightColorScheme(
    primary = Color(0xFF236C23),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFAAF5A5),
    onPrimaryContainer = Color(0xFF002201),
    inversePrimary = Color(0xFF8ED88A),
    secondary = Color(0xFF526350),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD4E8D2),
    onSecondaryContainer = Color(0xFF101F0F),
    tertiary = Color(0xFF2D676C),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFB2EDF2),
    onTertiaryContainer = Color(0xFF002022),
    error = Color(0xFFB4271F),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD4),
    onErrorContainer = Color(0xFF410000),
    background = Color(0xFFF9FDF9),
    onBackground = Color(0xFF191C19),
    surface = Color(0xFFF9FDF9),
    onSurface = Color(0xFF191C19),
    surfaceVariant = Color(0xFFDCE5DB),
    onSurfaceVariant = Color(0xFF414940),
    outline = Color(0xFF717970),
    outlineVariant = Color(0xFFC0C9BF),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF2E312E),
    inverseOnSurface = Color(0xFFEEF2ED),
    surfaceDim = Color(0xFFD7DBD7),
    surfaceBright = Color(0xFFF6FAF6),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF0F5F0),
    surfaceContainer = Color(0xFFEBEFEA),
    surfaceContainerHigh = Color(0xFFE5E9E5),
    surfaceContainerHighest = Color(0xFFDFE4DF),
    surfaceTint = Color(0xFF236C23),
)

internal val GREENDarkColors = darkColorScheme(
    primary = Color(0xFF8ED88A),
    onPrimary = Color(0xFF003A02),
    primaryContainer = Color(0xFF005305),
    onPrimaryContainer = Color(0xFFAAF5A5),
    inversePrimary = Color(0xFF236C23),
    secondary = Color(0xFFB8CCB7),
    onSecondary = Color(0xFF253424),
    secondaryContainer = Color(0xFF3A4B39),
    onSecondaryContainer = Color(0xFFD4E8D2),
    tertiary = Color(0xFF96D0D6),
    onTertiary = Color(0xFF00363B),
    tertiaryContainer = Color(0xFF104E53),
    onTertiaryContainer = Color(0xFFB2EDF2),
    error = Color(0xFFFFB4A8),
    onError = Color(0xFF690001),
    errorContainer = Color(0xFF930003),
    onErrorContainer = Color(0xFFFFDAD4),
    background = Color(0xFF191C19),
    onBackground = Color(0xFFDFE4DF),
    surface = Color(0xFF191C19),
    onSurface = Color(0xFFDFE4DF),
    surfaceVariant = Color(0xFF414940),
    onSurfaceVariant = Color(0xFFC0C9BF),
    outline = Color(0xFF8A938A),
    outlineVariant = Color(0xFF414940),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFDFE4DF),
    inverseOnSurface = Color(0xFF2E312E),
    surfaceDim = Color(0xFF111411),
    surfaceBright = Color(0xFF373A36),
    surfaceContainerLowest = Color(0xFF0C0F0C),
    surfaceContainerLow = Color(0xFF191C19),
    surfaceContainer = Color(0xFF1D201D),
    surfaceContainerHigh = Color(0xFF282B27),
    surfaceContainerHighest = Color(0xFF323632),
    surfaceTint = Color(0xFF8ED88A),
)

internal val AMBERLightColors = lightColorScheme(
    primary = Color(0xFF8B5000),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDCBD),
    onPrimaryContainer = Color(0xFF2D1600),
    inversePrimary = Color(0xFFFFB874),
    secondary = Color(0xFF6E5B4A),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFF5DFCB),
    onSecondaryContainer = Color(0xFF281809),
    tertiary = Color(0xFF56633D),
    onTertiary = Color(0xFFFFFFFE),
    tertiaryContainer = Color(0xFFD9E8BD),
    onTertiaryContainer = Color(0xFF161F00),
    error = Color(0xFFB4271F),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD4),
    onErrorContainer = Color(0xFF410000),
    background = Color(0xFFFFFCF9),
    onBackground = Color(0xFF1E1B18),
    surface = Color(0xFFFFFCF9),
    onSurface = Color(0xFF1E1B18),
    surfaceVariant = Color(0xFFEBE1D7),
    onSurfaceVariant = Color(0xFF4E453E),
    outline = Color(0xFF7F756D),
    outlineVariant = Color(0xFFCFC5BC),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF33302D),
    inverseOnSurface = Color(0xFFF5F0EC),
    surfaceDim = Color(0xFFDED9D5),
    surfaceBright = Color(0xFFFDF8F4),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF8F3EF),
    surfaceContainer = Color(0xFFF2EDE9),
    surfaceContainerHigh = Color(0xFFECE7E3),
    surfaceContainerHighest = Color(0xFFE6E2DD),
    surfaceTint = Color(0xFF8B5000),
)

internal val AMBERDarkColors = darkColorScheme(
    primary = Color(0xFFFFB874),
    onPrimary = Color(0xFF4A2800),
    primaryContainer = Color(0xFF6A3C00),
    onPrimaryContainer = Color(0xFFFFDCBD),
    inversePrimary = Color(0xFF8B5000),
    secondary = Color(0xFFD8C3B0),
    onSecondary = Color(0xFF3E2D1D),
    secondaryContainer = Color(0xFF554333),
    onSecondaryContainer = Color(0xFFF5DFCB),
    tertiary = Color(0xFFBDCCA2),
    onTertiary = Color(0xFF29340F),
    tertiaryContainer = Color(0xFF3F4B26),
    onTertiaryContainer = Color(0xFFD9E8BD),
    error = Color(0xFFFFB4A8),
    onError = Color(0xFF690001),
    errorContainer = Color(0xFF930003),
    onErrorContainer = Color(0xFFFFDAD4),
    background = Color(0xFF1E1B18),
    onBackground = Color(0xFFE6E2DD),
    surface = Color(0xFF1E1B18),
    onSurface = Color(0xFFE6E2DD),
    surfaceVariant = Color(0xFF4E453E),
    onSurfaceVariant = Color(0xFFCFC5BC),
    outline = Color(0xFF998F87),
    outlineVariant = Color(0xFF4E453E),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE6E2DD),
    inverseOnSurface = Color(0xFF33302D),
    surfaceDim = Color(0xFF161310),
    surfaceBright = Color(0xFF3C3835),
    surfaceContainerLowest = Color(0xFF110E0B),
    surfaceContainerLow = Color(0xFF1E1B18),
    surfaceContainer = Color(0xFF221F1C),
    surfaceContainerHigh = Color(0xFF2D2926),
    surfaceContainerHighest = Color(0xFF383431),
    surfaceTint = Color(0xFFFFB874),
)

internal val ROSELightColors = lightColorScheme(
    primary = Color(0xFF9B3E61),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD9E4),
    onPrimaryContainer = Color(0xFF3E001D),
    inversePrimary = Color(0xFFFFB0C9),
    secondary = Color(0xFF71575F),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFADBE3),
    onSecondaryContainer = Color(0xFF2A151C),
    tertiary = Color(0xFF79573C),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDCC1),
    onTertiaryContainer = Color(0xFF2F1500),
    error = Color(0xFFB4271F),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD4),
    onErrorContainer = Color(0xFF410000),
    background = Color(0xFFFFFBFC),
    onBackground = Color(0xFF1F1A1C),
    surface = Color(0xFFFFFBFC),
    onSurface = Color(0xFF1F1A1C),
    surfaceVariant = Color(0xFFEEDFE3),
    onSurfaceVariant = Color(0xFF504447),
    outline = Color(0xFF817477),
    outlineVariant = Color(0xFFD1C3C7),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF342F30),
    inverseOnSurface = Color(0xFFF6EFF1),
    surfaceDim = Color(0xFFDFD8DA),
    surfaceBright = Color(0xFFFEF8F9),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF9F2F4),
    surfaceContainer = Color(0xFFF3ECEE),
    surfaceContainerHigh = Color(0xFFEDE6E8),
    surfaceContainerHighest = Color(0xFFE7E1E3),
    surfaceTint = Color(0xFF9B3E61),
)

internal val ROSEDarkColors = darkColorScheme(
    primary = Color(0xFFFFB0C9),
    onPrimary = Color(0xFF640333),
    primaryContainer = Color(0xFF7F234A),
    onPrimaryContainer = Color(0xFFFFD9E4),
    inversePrimary = Color(0xFF9B3E61),
    secondary = Color(0xFFDDBFC7),
    onSecondary = Color(0xFF412A31),
    secondaryContainer = Color(0xFF594047),
    onSecondaryContainer = Color(0xFFFADBE3),
    tertiary = Color(0xFFE6BFA1),
    onTertiary = Color(0xFF48290E),
    tertiaryContainer = Color(0xFF604025),
    onTertiaryContainer = Color(0xFFFFDCC1),
    error = Color(0xFFFFB4A8),
    onError = Color(0xFF690001),
    errorContainer = Color(0xFF930003),
    onErrorContainer = Color(0xFFFFDAD4),
    background = Color(0xFF1F1A1C),
    onBackground = Color(0xFFE7E1E3),
    surface = Color(0xFF1F1A1C),
    onSurface = Color(0xFFE7E1E3),
    surfaceVariant = Color(0xFF504447),
    onSurfaceVariant = Color(0xFFD1C3C7),
    outline = Color(0xFF9B8D91),
    outlineVariant = Color(0xFF504447),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE7E1E3),
    inverseOnSurface = Color(0xFF342F30),
    surfaceDim = Color(0xFF171213),
    surfaceBright = Color(0xFF3D3839),
    surfaceContainerLowest = Color(0xFF110D0E),
    surfaceContainerLow = Color(0xFF1F1A1C),
    surfaceContainer = Color(0xFF231E20),
    surfaceContainerHigh = Color(0xFF2E292A),
    surfaceContainerHighest = Color(0xFF393335),
    surfaceTint = Color(0xFFFFB0C9),
)

/**
 * The scheme for [source], or `null` where there is none to resolve.
 *
 * `null` for [ColorSource.WALLPAPER], which is the *device's* palette and can only be read at
 * runtime, and for [ColorSource.TEAL], which lives in `Color.kt` with the rest of the hand-authored
 * scheme. Keeping both out of here rather than duplicating them means there is exactly one place a
 * given scheme is written down.
 */
internal fun generatedColorScheme(source: ColorSource, dark: Boolean): ColorScheme? = when (source) {
    ColorSource.WALLPAPER, ColorSource.TEAL -> null
    ColorSource.PURPLE -> if (dark) PURPLEDarkColors else PURPLELightColors
    ColorSource.BLUE -> if (dark) BLUEDarkColors else BLUELightColors
    ColorSource.GREEN -> if (dark) GREENDarkColors else GREENLightColors
    ColorSource.AMBER -> if (dark) AMBERDarkColors else AMBERLightColors
    ColorSource.ROSE -> if (dark) ROSEDarkColors else ROSELightColors
}
